struct testG<T> {
    T x;
}
void doSmnth<T>() {
}
int main() {
    doSmnth<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<testG<int>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>();
}
